# Generated by Django 4.0.5 on 2022-06-19 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shout', '0002_shout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shout', to=settings.AUTH_USER_MODEL),
        ),
    ]
