# Generated by Django 4.0.5 on 2022-06-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shout', '0003_alter_shout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
